### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by TDLaouer** [SkyrimTogether/issues-server#1]
Hey guys, just here to report a bug, thanks for your hard work!
![Screenshot_24](https://user-images.githubusercontent.com/36383161/57979871-942e0a00-7a23-11e9-8d3f-9d347c4a6403.png)

**Comment by MasterMNB** [comment]
Latest Server and Client Version without SkyUI.

```
  {"date":"2019-05-23 17:33:58,704", "level":"INFO", "event":"create_spawned_npc", "connection_id":2, "npc_name":"Draugr", "cell_name":"Ödsturzhügelgrab: Tempel" }
   {"date":"2019-05-23 17:33:58,704", "level":"DEBUG", "event":"add_container", "server_id":43, "is_actor":1 }
   {"date":"2019-05-23 17:33:59,708", "level":"INFO", "event":"create_common_npc", "name":"Draugr", "ref_id":524454, "form_id":956568, "server_id":44, "host_connection_id":2, "health":50 } 
   {"date":"2019-05-23 17:33:59,708", "level":"DEBUG", "event":"add_container", "server_id":44, "is_actor":1 }
   {"date":"2019-05-23 17:34:02,393", "level":"INFO", "event":"process_actor_died", "health":-60.8223 }
   {"date":"2019-05-23 17:34:02,819", "level":"INFO", "event":"create_common_npc", "name":"Draugr", "ref_id":230391, "form_id":956565, "server_id":45, "host_connection_id":2, "health":50 }
   {"date":"2019-05-23 17:34:02,819", "level":"DEBUG", "event":"add_container", "server_id":45, "is_actor":1 }
   {"date":"2019-05-23 17:34:14,263", "level":"INFO", "event":"create_common_npc", "name":"Draugr", "ref_id":230380, "form_id":956574, "server_id":46, "
   host_connection_id":2, "health":50 }
   {"date":"2019-05-23 17:34:14,263", "level":"DEBUG", "event":"add_container", "server_id":46, "is_actor":1 }
   {"date":"2019-05-23 17:34:16,911", "level":"INFO", "event":"create_common_npc", "name":"Draugr", "ref_id":230392, "form_id":956569, "server_id":47, "host_connection_id":2, "health":50 }
   {"date":"2019-05-23 17:34:16,911", "level":"DEBUG", "event":"add_container", "server_id":47, "is_actor":1 }
   {"date":"2019-05-23 17:34:18,367", "level":"INFO", "event":"process_actor_died", "health":-18.6919 }
   Caught signal 11 (Segmentation fault) in program  [1]
      thread frame     IP       function
     [-1034567368]  0: 0x7f84c22f6e7e: <unknown> 
     [-1034567368]  1: 0x7f84c22faf78: <unknown> 
     [-1034567368]  2: 0x7f84c22fb401: <unknown> 
     [-1034567368]  3: 0x7f84c22dd21d: <unknown> 
     [-1034567368]  4: 0x7f84c22f2d41: <unknown>
     [-1034567368]  5: 0x7f84c216c38d: <unknown> 
     [-1034567368]  6: 0x7f84c20d667f: <unknown> 
     [-1034567368]  7: 0x7f84c23c40e3: <unknown>
Backtrace: 0x7f84c22f6e7e 0x7f84c22faf78 0x7f84c22fb401 0x7f84c22dd21d 0x7f84c22f2d41 0x7f84c216c38d 0x7f84c20d667f 0x7f84c23c40e3

```

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [1946718520]  0: 0x7f4173e067e9: <unknown>
  [1946718520]  1: 0x7f4173e0bfc9: <unknown>
  [1946718520]  2: 0x7f4173e0b4cc: <unknown>
  [1946718520]  3: 0x7f4173e0b76e: <unknown>
  [1946718520]  4: 0x7f4173e2a5f3: <unknown>
  [1946718520]  5: 0x7f4173e03c44: <unknown>
  [1946718520]  6: 0x7f4173e1fdeb: <unknown>
  [1946718520]  7: 0x7f4173c9938d: <unknown>
  [1946718520]  8: 0x7f4173c0367f: <unknown>
  [1946718520]  9: 0x7f4173ef1163: <unknown>

Backtrace: 0x7f4173e067e9 0x7f4173e0bfc9 0x7f4173e0b4cc 0x7f4173e0b76e 0x7f4173e2a5f3 0x7f4173e03c44 0x7f4173e1fdeb 0x7f4173c9938d 0x7f4173c0367f 0x7f4173ef1163

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [1293746488]  0: 0x7f584cf6a0c0: netcode_network_simulator_send_packet(netcode_network_simulator_t*, netcode_address_t*, netcode_address_t*, unsigned char*, int)()+0x30
  [1293746488]  1: 0x7f584cf6cd0e: netcode_server_send_client_packet(netcode_server_t*, void*, int)()+0xce
  [1293746488]  2: 0x7f584cf6e5a1: netcode_server_send_packet()+0xc1
  [1293746488]  3: 0x7f584cf6ff0f: reliable_endpoint_send_packet()+0x26f
  [1293746488]  4: 0x7f584cf5210c: yojimbo::Server::SendPackets()()+0xcc
  [1293746488]  5: 0x7f584cf66359: YojimboServer::Update()()+0x2e9
  [1293746488]  6: 0x7f584cddf64d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [1293746488]  7: 0x7f584cd496cf: main()+0x18f
  [1293746488]  8: 0x7f584d037463: __libc_start_main()+0x33

Backtrace: 0x7f584cf6a0c0 0x7f584cf6cd0e 0x7f584cf6e5a1 0x7f584cf6ff0f 0x7f584cf5210c 0x7f584cf66359 0x7f584cddf64d 0x7f584cd496cf 0x7f584d037463

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [488665400]  0: 0x7f761cfa10c0: netcode_network_simulator_send_packet(netcode_network_simulator_t*, netcode_address_t*, netcode_address_t*, unsigned char*, int)()+0x30
  [488665400]  1: 0x7f761cfa3d0e: netcode_server_send_client_packet(netcode_server_t*, void*, int)()+0xce
  [488665400]  2: 0x7f761cfa55a1: netcode_server_send_packet()+0xc1
  [488665400]  3: 0x7f761cfa6f0f: reliable_endpoint_send_packet()+0x26f
  [488665400]  4: 0x7f761cf8910c: yojimbo::Server::SendPackets()()+0xcc
  [488665400]  5: 0x7f761cf9d359: YojimboServer::Update()()+0x2e9
  [488665400]  6: 0x7f761ce1664d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [488665400]  7: 0x7f761cd806cf: main()+0x18f
  [488665400]  8: 0x7f761d06e463: __libc_start_main()+0x33

Backtrace: 0x7f761cfa10c0 0x7f761cfa3d0e 0x7f761cfa55a1 0x7f761cfa6f0f 0x7f761cf8910c 0x7f761cf9d359 0x7f761ce1664d 0x7f761cd806cf 0x7f761d06e463

**Comment by bacitoto** [comment]
I tried to crash my game, fought the 1st dragon quest, player.setav speedmult 3000 ran all over Skyrim, went to the edge of the world connected and disconnected, loaded save-files without disconnecting. NOTHING

This error is quite random as it seems, can't find how to reproduce it
```

Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [-231960264]  0: 0x7f82f20630c0: netcode_network_simulator_send_packet(netcode_network_simulator_t*, netcode_address_t*, netcode_address_t*, unsigned char*, int)()+0x30
  [-231960264]  1: 0x7f82f2065d0e: netcode_server_send_client_packet(netcode_server_t*, void*, int)()+0xce
  [-231960264]  2: 0x7f82f20675a1: netcode_server_send_packet()+0xc1
  [-231960264]  3: 0x7f82f2069048: reliable_endpoint_send_packet()+0x3a8
  [-231960264]  4: 0x7f82f204b10c: yojimbo::Server::SendPackets()()+0xcc
  [-231960264]  5: 0x7f82f205f359: YojimboServer::Update()()+0x2e9
  [-231960264]  6: 0x7f82f1ed864d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [-231960264]  7: 0x7f82f1e426cf: main()+0x18f
  [-231960264]  8: 0x7f82f2130463: __libc_start_main()+0x33

Backtrace: 0x7f82f20630c0 0x7f82f2065d0e 0x7f82f20675a1 0x7f82f2069048 0x7f82f204b10c 0x7f82f205f359 0x7f82f1ed864d 0x7f82f1e426cf 0x7f82f2130463
```

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [355746104]  0: 0x7efc150e272b: netcode_server_free_packet()+0xb
  [355746104]  1: 0x7efc150bdf53: yojimbo::Server::ReceivePackets()()+0x93
  [355746104]  2: 0x7efc150da0eb: YojimboServer::Update()()+0x7b
  [355746104]  3: 0x7efc14f5364d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [355746104]  4: 0x7efc14ebd6cf: main()+0x18f
  [355746104]  5: 0x7efc151ab463: __libc_start_main()+0x33

Backtrace: 0x7efc150e272b 0x7efc150bdf53 0x7efc150da0eb 0x7efc14f5364d 0x7efc14ebd6cf 0x7efc151ab463

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [1386246456]  0: 0x7f35527a10c0: netcode_network_simulator_send_packet(netcode_network_simulator_t*, netcode_address_t*, netcode_address_t*, unsigned char*, int)()+0x30
  [1386246456]  1: 0x7f35527a3d0e: netcode_server_send_client_packet(netcode_server_t*, void*, int)()+0xce
  [1386246456]  2: 0x7f35527a55a1: netcode_server_send_packet()+0xc1
  [1386246456]  3: 0x7f35527a6f0f: reliable_endpoint_send_packet()+0x26f
  [1386246456]  4: 0x7f355278910c: yojimbo::Server::SendPackets()()+0xcc
  [1386246456]  5: 0x7f355279d359: YojimboServer::Update()()+0x2e9
  [1386246456]  6: 0x7f355261664d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [1386246456]  7: 0x7f35525806cf: main()+0x18f
  [1386246456]  8: 0x7f355286e463: __libc_start_main()+0x33

Backtrace: 0x7f35527a10c0 0x7f35527a3d0e 0x7f35527a55a1 0x7f35527a6f0f 0x7f355278910c 0x7f355279d359 0x7f355261664d 0x7f35525806cf 0x7f355286e463

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [-141827784]  0: 0x7febf76581fe: netcode_network_simulator_receive_packets(netcode_network_simulator_t*, netcode_address_t*, int, unsigned char**, int*, netcode_address_t*)()+0xe
  [-141827784]  1: 0x7febf765c2f8: netcode_server_receive_packets(netcode_server_t*)()+0x88
  [-141827784]  2: 0x7febf765c781: netcode_server_update()+0x11
  [-141827784]  3: 0x7febf763e51d: yojimbo::Server::AdvanceTime(double)()+0x3d
  [-141827784]  4: 0x7febf76540c1: YojimboServer::Update()()+0x51
  [-141827784]  5: 0x7febf74cd64d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [-141827784]  6: 0x7febf74376cf: main()+0x18f
  [-141827784]  7: 0x7febf7725463: __libc_start_main()+0x33

Backtrace: 0x7febf76581fe 0x7febf765c2f8 0x7febf765c781 0x7febf763e51d 0x7febf76540c1 0x7febf74cd64d 0x7febf74376cf 0x7febf7725463

**Comment by therealcuzin** [comment]
Hey guys, I am having a similar problem occur where my server crashes randomly. Me and a friend have been trying to find a pattern however we haven't managed to find one. 

I see you guys get some server feedback when yours crashes, however my server window just closes with no feedback at all. I even went through the server logs and nothing was shown.

We are running Skyrim Special Edition Version 1.5.73.0.8 with no mods installed.

**Comment by Kiaos** [comment]
We are using the docker image not windows server but im sure its the same crash. docker is more stable than ruining the windows server version. The most stable version is Linux.

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [-105217736]  0: 0x7ff8f99420c0: netcode_network_simulator_send_packet(netcode_network_simulator_t*, netcode_address_t*, netcode_address_t*, unsigned char*, int)()+0x30
  [-105217736]  1: 0x7ff8f9944d0e: netcode_server_send_client_packet(netcode_server_t*, void*, int)()+0xce
  [-105217736]  2: 0x7ff8f99465a1: netcode_server_send_packet()+0xc1
  [-105217736]  3: 0x7ff8f9947f0f: reliable_endpoint_send_packet()+0x26f
  [-105217736]  4: 0x7ff8f992a10c: yojimbo::Server::SendPackets()()+0xcc
  [-105217736]  5: 0x7ff8f993e359: YojimboServer::Update()()+0x2e9
  [-105217736]  6: 0x7ff8f97b764d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [-105217736]  7: 0x7ff8f97216cf: main()+0x18f
  [-105217736]  8: 0x7ff8f9a0f463: __libc_start_main()+0x33

Backtrace: 0x7ff8f99420c0 0x7ff8f9944d0e 0x7ff8f99465a1 0x7ff8f9947f0f 0x7ff8f992a10c 0x7ff8f993e359 0x7ff8f97b764d 0x7ff8f97216cf 0x7ff8f9a0f463

**Comment by Kiaos** [comment]
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [174588216]  0: 0x7f960a41a1fe: netcode_network_simulator_receive_packets(netcode_network_simulator_t*, netcode_address_t*, int, unsigned char**, int*, netcode_address_t*)()+0xe
  [174588216]  1: 0x7f960a41e2f8: netcode_server_receive_packets(netcode_server_t*)()+0x88
  [174588216]  2: 0x7f960a41e781: netcode_server_update()+0x11
  [174588216]  3: 0x7f960a40051d: yojimbo::Server::AdvanceTime(double)()+0x3d
  [174588216]  4: 0x7f960a4160c1: YojimboServer::Update()()+0x51
  [174588216]  5: 0x7f960a28f64d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d
  [174588216]  6: 0x7f960a1f96cf: main()+0x18f
  [174588216]  7: 0x7f960a4e7463: __libc_start_main()+0x33

Backtrace: 0x7f960a41a1fe 0x7f960a41e2f8 0x7f960a41e781 0x7f960a40051d 0x7f960a4160c1 0x7f960a28f64d 0x7f960a1f96cf 0x7f960a4e7463

**Comment by seefo** [comment]
```Caught signal 11 (Segmentation fault) in program  [1]




   thread frame     IP       function


  [-1139617480]  0: 0x7fdabbec71fe: netcode_network_simulator_receive_packets(netcode_network_simulator_t*, netcode_address_t*, int, unsigned char**, int*, netcode_address_t*)()+0xe


  [-1139617480]  1: 0x7fdabbecb2f8: netcode_server_receive_packets(netcode_server_t*)()+0x88


  [-1139617480]  2: 0x7fdabbecb781: netcode_server_update()+0x11


  [-1139617480]  3: 0x7fdabbead51d: yojimbo::Server::AdvanceTime(double)()+0x3d


  [-1139617480]  4: 0x7fdabbec30c1: YojimboServer::Update()()+0x51


  [-1139617480]  5: 0x7fdabbd3c64d: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)()+0x5d


  [-1139617480]  6: 0x7fdabbca66cf: main()+0x18f


  [-1139617480]  7: 0x7fdabbf94463: __libc_start_main()+0x33```

**Repro (Windows 10 x64, fullscreen + borderless):**
1. Connect to a server
2. Press `ctrl + alt + delete`, wait until system options appear
3. Click Task Manager
4. Server will segfault, disconnecting all users

The repro seemed to work for me, I repro'd it several times. I might be missing a step, so let me know if you can't repro it from these steps.

**Comment by leahcimrm12** [comment]
Same happening for me in docker container running in chromiumOS on a GCP instance:

{"date":"2019-07-27 01:22:21,676", "level":"INFO", "event":"create_spawned_npc", "connection_id":3, "npc_name":"Whiterun Guard", "cell_name":"Whiterun" }
{"date":"2019-07-27 01:22:21,676", "level":"DEBUG", "event":"add_container", "server_id":204, "is_actor":1 }
{"date":"2019-07-27 01:22:21,676", "level":"INFO", "event":"create_spawned_npc", "connection_id":3, "npc_name":"Whiterun Guard", "cell_name":"Whiterun" }
{"date":"2019-07-27 01:22:21,676", "level":"DEBUG", "event":"add_container", "server_id":205, "is_actor":1 }
{"date":"2019-07-27 01:22:21,676", "level":"INFO", "event":"create_spawned_npc", "connection_id":3, "npc_name":"Whiterun Guard", "cell_name":"Whiterun" }
{"date":"2019-07-27 01:22:21,676", "level":"DEBUG", "event":"add_container", "server_id":206, "is_actor":1 }
{"date":"2019-07-27 01:22:27,021", "level":"DEBUG", "event":"spell_cast_send", "player_id":1 }
{"date":"2019-07-27 01:22:27,021", "level":"DEBUG", "event":"spell_cast_send", "player_id":2 }
{"date":"2019-07-27 01:22:28,839", "level":"INFO", "event":"create_spawned_npc", "connection_id":3, "npc_name":"Whiterun Guard", "cell_name":"Whiterun" }
{"date":"2019-07-27 01:22:28,839", "level":"DEBUG", "event":"add_container", "server_id":207, "is_actor":1 }
{"date":"2019-07-27 01:22:28,839", "level":"INFO", "event":"create_spawned_npc", "connection_id":3, "npc_name":"Whiterun Guard", "cell_name":"Whiterun" }
{"date":"2019-07-27 01:22:28,839", "level":"DEBUG", "event":"add_container", "server_id":208, "is_actor":1 }
Caught signal 11 (Segmentation fault) in program  [1]

   thread frame     IP       function
  [-492281544]  0: 0x7f5ee28204e0: netcode_network_simulator_send_packet(netcode_network_simulator_t*, netcode_address_t*, netcode_address_t*, unsigned char*, int)()+0x30
  [-492281544]  1: 0x7f5ee282312e: netcode_server_send_client_packet(netcode_server_t*, void*, int)()+0xce
  [-492281544]  2: 0x7f5ee28249c1: netcode_server_send_packet()+0xc1
  [-492281544]  3: 0x7f5ee282632f: reliable_endpoint_send_packet()+0x26f
  [-492281544]  4: 0x7f5ee280850c: yojimbo::Server::SendPackets()()+0xcc
  [-492281544]  5: 0x7f5ee281c779: YojimboServer::Update()()+0x2e9
  [-492281544]  6: 0x7f5ee2695a35: Run(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)()+0xc5
  [-492281544]  7: 0x7f5ee25ff81b: main()+0x1eb
  [-492281544]  8: 0x7f5ee28ed883: __libc_start_main()+0x33

Backtrace: 0x7f5ee28204e0 0x7f5ee282312e 0x7f5ee28249c1 0x7f5ee282632f 0x7f5ee280850c 0x7f5ee281c779 0x7f5ee2695a35 0x7f5ee25ff81b 0x7f5ee28ed883

**Comment by yamashi** [comment]
These have all been fixed by using  another net lib.
