### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by skyl4ke** [SkyrimTogether/issues-server#11]
## Description

I have a problem with my own server. When i open the server.exe, i can join with 127.0.0.1 and my ipv4 address but anyone can't join to this serwer(except me). Im tried with my friend and with one guy from discord. I do port forwarding with with multiple ways, tried to turn off Windows defender, open server.exe with administrator. I can join to public servers and guy from discord server. I cant' join to my friend server.

## Reproduction rate

Everytime i can reproduce it.

## Your environment

* Launcher version:

1.0.6

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

## Evidence (optional)

Show us what happen.
{"date":"2019-08-13 13:24:53,408", "level":"INFO", "event":"server_state", "value":"started", "token":"" }
{"date":"2019-08-13 13:25:31,669", "level":"INFO", "event":"connected", "connection_id":2001938699 }
{"date":"2019-08-13 13:25:31,688", "level":"INFO", "event":"hello_received", "client_protocol":3574881509, "server_protocol":3574881509 }
{"date":"2019-08-13 13:25:32,005", "level":"INFO", "event":"hello", "connection_id":2001938699, "name":"sdaadsa" }

**Comment by yamashi** [comment]
This is not support but bug reports.
