### ISSUE TITLE
Two players entering a room at the same time will crash

### ISSUE THREAD

**Issue by zxyxz** [SkyrimTogether/issues-server#13]
## Description

Two players entering a room at the same time will crash

## Steps to reproduce

How to reproduce this issue:

1. connect
2. Player 1 enters the room
3. Player 2 enters the room
4. Player 2 jumps out of the desktop

## Reproduction rate

Every time

## Expected result

return to normal

## Your environment

* Launcher version: 
1. harbor 1.0.6

docker :
`docker run -p 10578:10578/udp tiltedphoques/st-game-server`
* Game edition (choose on which edition do you have problems):
     The Elder Scrolls V: Skyrim Special Edition 1.5.80

* Operating system (choose one):
     Windows 10 x64

## Evidence (optional)

No error log

The problem occurred in the latest version update.
Version:
> Nightly:TiltedPhoqes/Head@b17b76ba0

**Comment by zxyxz** [comment]
NPC crashes when multiple players trigger the plot at the same time

**Comment by keinou** [comment]
This problem also occurs in oldrim.

**Comment by Pokang** [comment]
Wrong issueboard, please use the issues-game one, as this is related to the client and not the server, thanks!
