### ISSUE TITLE
server not starting properly

### ISSUE THREAD

**Issue by gibarel1** [SkyrimTogether/issues-server#14]
## Description

Server  does not start properly and only give one line in cmd and players are not able to connect (sometimes not even the host can connect)

## Steps to reproduce

1. Start server.exe.

## Reproduction rate

100% of the time

## Expected result

Server opens normaly giving two lines and players are not able to connect

## Your environment

* Launcher version: 1.0.6

* Game edition :
    * The Elder Scrolls V: Skyrim

* Operating system:

    * Windows 10 x64

## Evidence 

![Capturar](https://user-images.githubusercontent.com/21283067/65191033-1ae20a80-da49-11e9-8f09-badb38a6d1ad.PNG)

my friend is having the same issue with the server and we both downloaded the mod today 18/09/2019

**Comment by cikeZ00** [comment]
This is normal, as of the update which introduced the new Network Library.

I would recommend closing the issue as this is intended to happen.

**Comment by cikeZ00** [comment]
As a side note, you probably have a firewall issue. I would recommend disabling it

**Comment by gibarel1** [comment]
i have already disabled firewall and the problem is the fact that no one can join the server

**Comment by Pokang** [comment]
cikeZ00 is right, closing accordingly.
