### ISSUE TITLE
"npc_is_null" error when connecting via external IP

### ISSUE THREAD

**Issue by pengarty** [SkyrimTogether/issues-server#2]
## Description

I receive the following server error when connecting to my server via external IP.

> **"level":"ERROR", "event":"player_dtor_find_new_cell_host", "error":"npc_is_null"**

Takes place about 5 seconds after hitting connect.

Using my local IP, I connect without getting this error.

## Steps to reproduce

How to reproduce this issue:

1. Launch the game through Harbor.
2. Connect to server with external IP.
3. Wait for error to appear.

## Reproduction rate

100% of the time.

## Expected result

Should connect without problems.

## Your environment

* Launcher version: 1.0.5

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system (choose one):
    * Windows 10 x64

**Comment by WillabyNeko** [comment]
I have the same issue, regardless of local or external IP connection via myself and others who are trying to connect to my server.

**Comment by pengarty** [comment]
I suspect the real issue is the server can't actually set the player as the cell host and just fails to connect.

**Comment by nSimonFR** [comment]
I've been running into the same issue, and I managed to fix it by updating the server image.
They miss-typed their docker organization name and just renamed it recently, so make sure you are using the `tiltedphoques/st-game-server` image, **NOT** `titledphoques/st-game-server` (Notice the missplaced "**t**" in the org name).
The first links and install steps they provided for the server are now broken, as new images are only being uploaded to the new docker endpoint - thankfully they've updated their documentation.

**Comment by F1r3w477** [comment]
The issue arises if you are using an old, outdated version of the server. If you update the server to the newest version, there shouldn't be this issue.
