### ISSUE TITLE
My server crashes randomly

### ISSUE THREAD

**Issue by abusiv0** [SkyrimTogether/issues-server#4]
The title summarizes everything, the server is simply closed randomly and the console shows this:

https://i.imgur.com/HGEURXv.png

SO: Windows 10 x64 bits
Hardware: 
MSI B85-g43 Gaming
i5 4690 3.9 ghz
Ram: Ballistik Elite DDR3 1600 mhz

Skyrim: SkyrimSE - WITHOUT MODS 100% fresh.

How to reproduce? I do not know, it seems to be randomly.

**Comment by bacitoto** [comment]
[this issue is already opened here](https://github.com/SkyrimTogether/issues-server/issues/1)

**Comment by evanirla** [comment]
Also having these issues on my machine.

XEON W3530
6GB ECC
Windows 10 PRO
[logs.zip](https://github.com/SkyrimTogether/issues-server/files/3250496/logs.zip)

**Comment by rzjnzk** [comment]
This issue should either be closed and referenced in the duplicate, or the have to title changed to mention the segfault.

I'n my case, I experience random crashing, though there is notification of a segfault in the console. It appears that is also the case with @evanirla.

---

In my instance, my server crashes with no error information, and the process exits with an error code of 5. All times this has happened it has been after approximately 4 mins of successful cooperative play, and my player character is withing proximity of another player character. I can not verify that these are definitely factors, however. After the server crashes, both players remain in the world.
