### ISSUE TITLE
Docker port flag

### ISSUE THREAD

**Issue by Thepenguin9** [SkyrimTogether/issues-server#6]
## Description

Add the ability to open a different port for the server, so multiple st-servers can all run on the same docker server

## Additional context

This functionality exists via a batch file apparently, but I am unsure if this carries over to the docker server

**Comment by Neusor** [comment]
Just add the -port parameter when you run the docker server instance, it should work
-port 12345 for example

**Comment by Thepenguin9** [comment]
Well I'll be. Could this be added to the docker documentation for future reference? (along with any other flags available)
