### ISSUE TITLE
Shadowcloak of Nocturnal invisibility not showing up on other player's clients

### ISSUE THREAD

**Issue by jakebelle** [SkyrimTogether/issues-server#7]
## Description

The Enchantment "Shadowcloak of Nocturnal"'s invisibility effect is not showing on other player's clients, unlike the invisibility spell.

## Steps to reproduce

How to reproduce this issue:

1. Join a server
2. Have a piece of gear that has the enchantment "Shadowcloak of Nocturnal"
3. Crouch
4. Ask a player if you are invisible (on their screen you are just crouching and not invisible however you will see yourself as invisible)

## Reproduction rate

So far, 5/5 people, I've asked have said I'm not invisible on their screen when crouching while I'm invisible on my screen (here is the gear code playerenchantobject 10eb5c 1058a9 17121)

## Expected result

A visual effect similar to the invisibility spell when crouching with a piece of gear that has the enchantment

## Your environment

* Launcher version: 1.0.6

* Game edition:
    * The Elder Scrolls V: Skyrim Special Edition

* Operating system:
    * Windows 10 x64

## Evidence (optional)

None

**Comment by yamashi** [comment]
This isn't a server issue.
